language: node_js

node_js:
  - "6"

services:
  - couchdb
  - docker

env:
  - GOPATH=${TRAVIS_BUILD_DIR}/_workspace

hosts:
    - alice.cozy.local
    - bob.cozy.local
    - charlie.cozy.local

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  # start couchdb 2 (docker)
  - docker run -d -p 5984:5984 --name couch klaemo/couchdb:2.0.0
  # go 1.7
  - eval "$(gimme 1.7)"
  - mkdir $GOPATH
  # install stack v3
  - go get -u github.com/cozy/cozy-stack
  # start a stack v3 instance from master (listening on 8080)
  - curl -X PUT http://127.0.0.1:5984/{_users,_replicator,_global_changes}
  - $GOPATH/bin/cozy-stack serve --assets=$GOPATH/src/github.com/cozy/cozy-stack/assets &
  - sleep 1
  - $GOPATH/bin/cozy-stack instances add --dev "localhost:8080"
  # install stack v2
  - npm install -g coffee-script
  # start a stack v2 from NPM (listening on 9104 & 9101)
  - NODE_ENV=test NAME=datasystem TOKEN=token npm explore cozy-data-system npm run start &
  - sleep 3
  - npm explore cozy-proxy npm run postinstall
  - NODE_ENV=test NAME=proxy TOKEN=token npm explore cozy-proxy npm run start &
  - sleep 3
  - npm explore cozy-data-system coffee commands.coffee test-install client-js ../../test/package.json
  - export NAME=client-js
  - export TOKEN=apptoken
  # install an application and generate the associated token
  # TODO: should use a CLI to install this application when permissions on /apps/ are added
  - "curl -X POST -H 'Accept: application/vnd.api+json' 'http://localhost:8080/apps/mini?Source=git://github.com/jinroh/cozy-mini.git'"
  - sleep 10
  - export COZY_STACK_TOKEN=$($GOPATH/bin/cozy-stack instances token-app "localhost:8080" "mini")

deploy:
  provider: npm
  email: npm@cozycloud.cc
  api_key:
    secure: IY7qwu9LGdCKJTWDtsFPtaB2WhJ3vXUXTCeYEss0kM9Q98RuTSQA7ibu4c2kCRMhI7A7WAmHnkR7kDciyJGltcWEhn8yaXiJMfYqzCbyyfC4xfP4GsvKTlEyg3gjTREaJRibPJsQDBwo0d6zSaB85D0ovml0DT3PZCcMxUDw94yq/ej6qK3OAKY1QEQTEwNEQUL6Rr2ryi3zQHj8bP8cpq5tAFPvgsngLbGZsG8r2Rj6aHYjw2uHH1ummdcfJ0PdoHKaik1V5JazqPRs+KpQRpgByJ/sC3lVB9JMkxTzZ8n2iDOaIFgmAs4XIn1K6aUWQGkUsDi2vBoq3nHWCuLGOkeKWaktUtkQkzaG/6pm7UCZOxRQrJbldLZZQqxTpAEIZ31nybSM7kqT86NXIZm55hstn5cqlQoC/Y0T/NorkTAF5OAhD+dX35iw4C+Wglj9YdDABEXbpXGfl4dlKehxj4BfliGuelVR26XU/xocJCjq8/MA6Y5bcu2mZHHI7VtmeGHAya54JbQaqYMWpttIwp8al/RZ2/oLtpq+HNvwNWf583z7fezzP8EUYbAUzG6LleybDpoDfJ/CbI3LqWcopnS8HspL10TnPqaqA9pjvbrZPSJlydUfgEHmiWneha4FKbgpPfefG4PHiieFVEMA4lmUxFWWL91fruHg56cDmbk=
  on:
    tags: true
    repo: cozy/cozy-client-js
